import { TypedArray } from '../../utils/Utils';
import {
    LegacySourceTexture, SourceTextureLayerWebGLUploadResult, SourceTextureWebGLUploadResult,
    TextureMipmapGroup, WebGLTextureUploadCtx
} from './Texture';
import { Texture2DLayer } from './Texture2D';
import { ContentBridge } from '../../ContentAPI';
import { CompressedPixelFormat } from '../../utils/Constants';
import { _Math } from '../../math/Math';
import { TextureDimension, TextureViewDimension } from './types';

export class Texture2DCompressed extends LegacySourceTexture {

    className() {
        return 'Texture2DCompressed';
    }

    constructor(source: TextureMipmapGroup<CompressTexture2DLayer>) {
        super(TextureDimension.D2, TextureViewDimension.D2, false);
        ContentBridge.textureCreate(this);
        this.source = source;
        this.source.syncData(this);
    }

    uploadWebGLImpl(ctx: WebGLTextureUploadCtx, disableCustomMipmap: boolean, needPOT: boolean): SourceTextureWebGLUploadResult {
        return this.source.uploadWebGL(ctx, ctx.gl.TEXTURE_2D, disableCustomMipmap, needPOT);
    }

    canAutoGenerateMipmap(): boolean {
        return false;
    }

    protected getAutoGeneratedMipmapByteSize() {
        return 0;
    }

    source: TextureMipmapGroup<CompressTexture2DLayer>;

}

type CompressTextureLayerSource = TypedArray;

/**
 * Upload layer for one compressed 2D texture level.
 */
export class CompressTexture2DLayer extends Texture2DLayer {
    source: CompressTextureLayerSource;
    format: CompressedPixelFormat;

    constructor(source: CompressTextureLayerSource) {
        super();
        this.source = source;
    }

    static create(source: CompressTextureLayerSource) {
        return new CompressTexture2DLayer(source);
    }

    setFormat(format: CompressedPixelFormat) {
        this.format = format;
        return this;
    }

    /**
     * @internal
     */
    uploadWebGL(ctx: WebGLTextureUploadCtx, target: number, level: number, _needPOT: boolean): SourceTextureLayerWebGLUploadResult {
        ctx.gl.compressedTexImage2D(target, level, this.format, this.width, this.height, 0, this.source, 0);

        return {
            is_pot: _Math.isPowerOfTwo(this.width) && _Math.isPowerOfTwo(this.height),
            byteSize: this.source.byteLength
        };
    }
}
